/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SessionId } from "./SessionId";
import { SessionIdCountArgs } from "./SessionIdCountArgs";
import { SessionIdFindManyArgs } from "./SessionIdFindManyArgs";
import { SessionIdFindUniqueArgs } from "./SessionIdFindUniqueArgs";
import { DeleteSessionIdArgs } from "./DeleteSessionIdArgs";
import { SessionIdService } from "../sessionId.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => SessionId)
export class SessionIdResolverBase {
  constructor(
    protected readonly service: SessionIdService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SessionId",
    action: "read",
    possession: "any",
  })
  async _sessionIdsMeta(
    @graphql.Args() args: SessionIdCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [SessionId])
  @nestAccessControl.UseRoles({
    resource: "SessionId",
    action: "read",
    possession: "any",
  })
  async sessionIds(
    @graphql.Args() args: SessionIdFindManyArgs
  ): Promise<SessionId[]> {
    return this.service.sessionIds(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => SessionId, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SessionId",
    action: "read",
    possession: "own",
  })
  async sessionId(
    @graphql.Args() args: SessionIdFindUniqueArgs
  ): Promise<SessionId | null> {
    const result = await this.service.sessionId(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SessionId)
  @nestAccessControl.UseRoles({
    resource: "SessionId",
    action: "delete",
    possession: "any",
  })
  async deleteSessionId(
    @graphql.Args() args: DeleteSessionIdArgs
  ): Promise<SessionId | null> {
    try {
      return await this.service.deleteSessionId(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
